version: '3'

services:
  next:
    build:
      context: .
      target: runner
    ports:
      - 127.0.0.1:3000:3000
    env_file: .env
    volumes:
      - .:/app

  migrations:
    build:
      context: .
      target: migrations
    env_file: .env
    volumes:
      - ./prisma:/app/prisma:ro

  db:
    image: postgres
    environment:
      POSTGRES_USER: job-board
      POSTGRES_PASSWORD: unsecure
