version: '3'

services:
  next:
    build:
      context: .
      target: runner
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - .:/app

  db:
    image: postgres
    environment:
      POSTGRES_USER: job-board
      POSTGRES_PASSWORD: unsecure
