version: '3'

services:
  next:
    build:
      context: .
      target: development
    ports:
      - 127.0.0.1:3000:3000
    env_file: .env
    command: yarn dev
    volumes:
      - .:/app

  migrations:
    build:
      context: .
      target: migrations
    env_file: .env
    volumes:
      - ./prisma:/app/prisma:ro

  db:
    image: postgres
    environment:
      POSTGRES_USER: job-board
      POSTGRES_PASSWORD: unsecure

  minio:
    image: bitnami/minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: unsecure
    ports:
      - 9000:9000
      - 9001:9001

  minio-setup:
    image: minio/mc
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "
      mc config host add docker http://minio:9000 root unsecure;
      mc mb docker/jobboard-logos;
      mc anonymous set download docker/jobboard-logos;
      exit 0;
      "
